hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  httpclient:
    enabled: true

headers:
  client-version: X-CLIENT-VERSION

zuul:
  routes:
    integration:
      path: /products/**
      serviceId: product
      stripPrefix: false
  debug:
    request: true